export const WORDS = [
    { word: "apocryphal", meaning: "Of doubtful authenticity; widely believed but not proven true." },
    { word: "abstruse", meaning: "Difficult to understand; obscure." },
    { word: "ameliorate", meaning: "To make something better; improve." },
    { word: "anodyne", meaning: "Not likely to offend or provoke; soothing but bland." },
    { word: "antediluvian", meaning: "Extremely old-fashioned; from a very long time ago." },
    { word: "assiduous", meaning: "Showing great care and persistent effort." },
    { word: "auspicious", meaning: "Promising success; favorable." },
    { word: "belie", meaning: "To give a false impression of; to contradict." },
    { word: "capricious", meaning: "Given to sudden changes in mood or behavior; unpredictable." },
    { word: "circumspect", meaning: "Cautious; considering all circumstances before acting." },
    { word: "cogent", meaning: "Clear, logical, and convincing." },
    { word: "conflate", meaning: "To combine two things into one, often mistakenly." },
    { word: "contrite", meaning: "Genuinely remorseful; repentant." },
    { word: "deferential", meaning: "Respectful and submissive toward another’s wishes." },
    { word: "delineate", meaning: "To describe or portray precisely; outline." },
    { word: "diaphanous", meaning: "Light, delicate, and translucent." },
    { word: "disabuse", meaning: "To persuade someone that a belief is mistaken." },
    { word: "ebullient", meaning: "Cheerful and full of energy." },
    { word: "efficacious", meaning: "Effective; producing the desired result." },
    { word: "egregious", meaning: "Outstandingly bad; shocking." },
    { word: "enervate", meaning: "To weaken or drain energy from." },
    { word: "ephemeral", meaning: "Lasting for a very short time." },
    { word: "equanimity", meaning: "Calmness and composure, especially in difficulty." },
    { word: "erstwhile", meaning: "Former; previous." },
    { word: "esoteric", meaning: "Intended for or understood by only a small group." },
    { word: "excoriate", meaning: "To criticize severely; to denounce." },
    { word: "fastidious", meaning: "Very attentive to detail; hard to please." },
    { word: "fractious", meaning: "Irritable and likely to argue; unruly." },
    { word: "garrulous", meaning: "Excessively talkative." },
    { word: "halcyon", meaning: "Calm and peaceful; happy and carefree." },
    { word: "iconoclast", meaning: "A person who attacks cherished beliefs or institutions." },
    { word: "impecunious", meaning: "Having little or no money." },
    { word: "inchoate", meaning: "Just beginning; not fully formed or developed." },
    { word: "insouciant", meaning: "Casually unconcerned; nonchalant." },
    { word: "inveterate", meaning: "Long-established; habitual." },
    { word: "laconic", meaning: "Using very few words." },
    { word: "languid", meaning: "Lacking energy; relaxed and slow." },
    { word: "mendacious", meaning: "Not telling the truth; lying." },
    { word: "mercurial", meaning: "Quickly changing mood; volatile." },
    { word: "munificent", meaning: "Very generous." },
    { word: "nebulous", meaning: "Vague or ill-defined." },
    { word: "obdurate", meaning: "Stubbornly refusing to change one’s opinion." },
    { word: "obviate", meaning: "To remove a need or problem; make unnecessary." },
    { word: "ostensible", meaning: "Appearing true, but not necessarily so." },
    { word: "parsimonious", meaning: "Unwilling to spend money; stingy." },
    { word: "perspicacious", meaning: "Having keen judgment and understanding." },
    { word: "perfunctory", meaning: "Done with minimal effort; lacking care." },
    { word: "prevaricate", meaning: "To speak evasively; avoid the truth." },
    { word: "propitious", meaning: "Favorable; likely to lead to success." },
    { word: "pulchritude", meaning: "Beauty (often used humorously)." },
    { word: "querulous", meaning: "Complaining in a petulant way." },
    { word: "recalcitrant", meaning: "Resisting authority or control; difficult to manage." },
    { word: "redoubtable", meaning: "Formidable; commanding respect." },
    { word: "recondite", meaning: "Little known; obscure; difficult." },
    { word: "sagacious", meaning: "Wise; having good judgment." },
    { word: "sanguine", meaning: "Optimistic; hopeful, especially in a tough situation." },
    { word: "solicitous", meaning: "Showing care or concern; attentive." },
    { word: "spurious", meaning: "False; not genuine." },
    { word: "stentorian", meaning: "Loud and powerful (a voice)." },
    { word: "taciturn", meaning: "Reserved or uncommunicative; saying little." },
    { word: "trenchant", meaning: "Sharp and effective; incisive." },
    { word: "ubiquitous", meaning: "Present everywhere; widespread." },
    { word: "vicissitude", meaning: "A change of circumstances, often unpleasant." },
    { word: "winsome", meaning: "Charming in a sweet, appealing way." },
    { word: "zealous", meaning: "Full of enthusiasm; intensely devoted." }
  ];
  